name    'noma4i/windows_xmltask'
version '0.0.2'
author 'noma4i'
license 'Apache'
summary 'Create windows schedule task from exported xml stored on puppet fileserver'
project_page 'https://github.com/noma4i/puppet-windows_xmltask'
dependency   'puppetlabs/powershell', '>= 1.0.1'
